### ISSUE TITLE
Odigos ui isn't working on centos7 vm

### ISSUE THREAD

**Issue by just-a-learning-person** [keyval-dev/odigos#1044]
**Describe the bug**
After installing odigos according to the official documentation, localhost:3000 is a black page.

**Expected behavior**
See the monitor.

**Screenshots**
![image](https://github.com/keyval-dev/odigos/assets/55468780/659503dd-7b62-47bb-b84c-967ef6935654)

**Desktop (please complete the following information):**
 - Centos 7
 - Firefox
 - Docker version 25.0.3, build 4debf41
 - kind v0.9.0 go1.15.2 linux/amd64
 - Kubectl: Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.19.1

**Additional context**
May have the same problem as issue#[979](https://github.com/keyval-dev/odigos/issues/979)

**Comment by just-a-learning-person** [comment]
It's a Firefox problem, use Google Chrome instead

**Comment by alonkeyval** [comment]
@just-a-learning-person  Thank you for reporting the issue. Could you please provide any console logs related to it?

**Comment by just-a-learning-person** [comment]
Sorry, haven't got any. But here is the Firefox information. 
![image](https://github.com/keyval-dev/odigos/assets/55468780/e3d2b5a3-1e3a-40b8-8318-c995da7c3d46)
Hope this helps a little.

**Comment by rauno56** [comment]
FYI I'm on Firefox and haven't encountered problems.

@just-a-learning-person, screenshot from the browser console(ctrl-Shift-i -> "Console") and frontend process' terminal would be helpful.

**Comment by just-a-learning-person** [comment]
@rauno56 Thanks for advice! I get some syntax errors from the console. 
![image](https://github.com/keyval-dev/odigos/assets/55468780/39059f52-1edf-4d96-9deb-273fb7cedcb8)

**Comment by rauno56** [comment]
The version of Firefox you're using is an old Extended Support Release based on v68(released 2019) which does not support optional chaining for example. Latter is probably one of the reasons it's failing.  The current ESR is definitely upwards of v100 and will likely work fine.

I'm using the default version that ships with my distro(v124) and that works fine.

Do you have an option to update your Firefox or continue using chrome, @just-a-learning-person?

**Comment by just-a-learning-person** [comment]
That's fine. I'll use chrome instead. Thanks for your help.
