### ISSUE TITLE
Permit https and authentification for prometheus and other selfhosted endpoint

### ISSUE THREAD

**Issue by YoranSys** [keyval-dev/odigos#19]
Hello, 
when we set an url starting with https:// the config on the gateway configmap has an http:// prefix.

Thank for your work, this sounds very promising

**Comment by edeNFed** [comment]
Thank you for reporting this issue.
This is now fixed in `v0.1.2`.
Before installing the helm chart again, make sure to run `helm repo update` to fetch the latest version.
