### ISSUE TITLE
Support for sending logs, metrics, traces to ZincObserve

### ISSUE THREAD

**Issue by prabhatsharma** [keyval-dev/odigos#207]
Greetings from ZincObserve team - https://github.com/zinclabs/zincobserve . Would love to see support for ZincObserve in odigo.

**Is your feature request related to a problem? Please describe.**
Support for sending logs, metrics and traces to ZincObserve

**Describe the solution you'd like**
A direct selection for ZincObserve in odigos that allows people to send logs, metrics and traces to ZincObserve. ZincObserve supports:

Logs - [JSON array](https://zinc.dev/docs/guide/api/ingestion/json/) or elasticsearch _bulk format
Metrics - Prometheus remote write
Traces - OTLP

Here are details around it - https://zinc.dev/docs/guide/ingestion/

There should not be really much to do for odigo team to achieve this as all the elements are already there.

**Describe alternatives you've considered**
use elasticsearch, opentelemtry, and prometheus enpoints separately.

**Additional context**
No

**Comment by tanujd11** [comment]
@edeNFed I can take a look at this.

**Comment by edeNFed** [comment]
@tanujd11 just following up, do you need any help?

**Comment by prabhatsharma** [comment]
We can close this. Openobserve-collector now natively supports auto-instrumentation of java,  .net,  nodejs, python and go.
