### ISSUE TITLE
Permit basic authentification, port, headers and path for prometheus and other selfhosted endpoint

### ISSUE THREAD

**Issue by YoranSys** [keyval-dev/odigos#21]
Hello,

Could you allow advanced users to set the full url of the endpoints,
and maybe on the front the port and protocol used by the gateway directly on the web page.

This would allow us to have,
- basic authentication support [rfc7617](https://www.rfc-editor.org/rfc/rfc7617.html) 
- custom port support
- path
- headers 

This will allow a good integration with a more complex architecture like this one: 

- Kube cluster A idigos-gateway> Kube cluster B loki ingress : 
  - https://user:password@mylokiserver.com:443/api/v1/push
  
- Kube cluster A idigos-gateway --> Kube cluster B tempo ingress :
  - https://user:password@mytemposerver.com:443/

What do you think about it?

**Comment by edeNFed** [comment]
Hi @YoranSys The latest version of Odigos (v0.1.33) added Generic OTLP destination which lets you define any URL.
You are welcome to check it out 😄
