### ISSUE TITLE
destinations page: add search

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#37]
As more and more destinations are added, it will be harder for users to find the exact destination they are looking for.
A common way to solve this problem is by implementing a search.
Search can probably happen on the client side.

**Comment by D-Lite** [comment]
Hi @edeNFed, you can assign this to me

**Comment by D-Lite** [comment]
https://github.com/keyval-dev/odigos/pull/138

**Comment by edeNFed** [comment]
closed by #138
