### ISSUE TITLE
Support applications running on serverless kubernetes services

### ISSUE THREAD

**Issue by hzhhong** [keyval-dev/odigos#391]
**Describe the solution you'd like**
Currently, instrumentation is achieved through device plugins, which are deployed through daemonsets. This approach does not work well in serverless services.

**Describe alternatives you've considered**

**Additional context**

**Comment by edeNFed** [comment]
This is on our roadmap and hopefully will be released soon 😄 I will keep you updated

**Comment by zijiwork** [comment]
Run on a Windows server to observe. net
