### ISSUE TITLE
Use dependabot group version updates for reducing pull requests

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#479]
Currently, every time a new Kubernetes version comes out or when a new OpenTelemetry instrumentation is updated, dependabot opens many pull requests for every dependency. We can use the [group version updates](https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/) feature of dependabot to open a single pull request that contains all the relevant dependencies changes.

**Comment by SzymonSt** [comment]
hello @edeNFed  I will have a look at that.
