### ISSUE TITLE
Installing odigos stack without version specified results in odigos pods failure.

### ISSUE THREAD

**Issue by SzymonSt** [keyval-dev/odigos#490]
**Describe the bug**
Installing odigos stack without version specified via cli results in odigos pods failure.

**To Reproduce**
1. Run odigos `cli install ` command without the `--version` tag specified.
2. Observe `InvalidImageName` status for odigos pods.

**Expected behavior**
If version isn't specifically set up `latest` should be apply even if this docker images tag doesn't exist yet.

**Screenshots**
![image](https://github.com/keyval-dev/odigos/assets/48925621/e807c9d3-6769-427e-b3c2-ec7a1285ce9b)

```
“Failed to apply default image tag "keyval/odigos-odiglet:": couldn't p
arse image reference "keyval/odigos-odiglet:": invalid reference format”
```

**Comment by SzymonSt** [comment]
I can have a look once it is labeled and confirmed by maintainers.

**Comment by blumamir** [comment]
Hi @SzymonSt , sorry about the late reply.

I use version v0.1.79 and it is able to work correctly on my setup.
Are you still experiencing the issue? can you please share the cli version you are using?

Thanks

**Comment by miravtmehta** [comment]
@blumamir Yes this exists 

```go
kubernetes-dashboard   kubernetes-dashboard-5c5cfc8747-6l5bc        1/1     Running            0              82m
odigos-system          odiglet-6ctks                                0/1     InvalidImageName   0              23s
odigos-system          odigos-autoscaler-5bdd96458d-cxlqk           0/1     InvalidImageName   0              22s
odigos-system          odigos-instrumentor-9d6f8f8b5-hndm6          0/1     InvalidImageName   0              25s
odigos-system          odigos-scheduler-7bdbf669c9-7jmw2            0/1     InvalidImageName   0              24s
tracing                jaeger-7fb96f9c57-8q9r6                      1/1     Running            0              65m
``` 

```shell
odigos version
Odigos Cli Version: version.Info{Version:'v1.0.0', GitCommit:'6977d54', BuildDate:'2023-10-31T12:44:18Z'}
Odigos Version (in cluster): version.Info{Version:'not installed in cluster'}
```
