### ISSUE TITLE
Uninstall cli process cleans up pods' templates but doesn't clean up namespace template.

### ISSUE THREAD

**Issue by SzymonSt** [keyval-dev/odigos#491]
**Describe the bug**
While uninstalling odigos via cli, label `odigos-instrumentation=enabled` in instrumented namespace isn't removed. This situation results with the issue with discovering services in affected namespaces while setting up odigos once again from scratch.

**To Reproduce**
1. Install odigos using cli .
2. Instrument services in one of the namespaces.
3. Uninstall odigos.
4. Try to configure instrumentation for same services in same namespace once again.

**Expected behavior**
No issues with discovering previously instrumented services during odigos reinstallation

**Screenshots**
During reinstrumentation:
![image](https://github.com/keyval-dev/odigos/assets/48925621/2dff1eb8-7788-4fbf-8ebd-e7c67146d058)
![image](https://github.com/keyval-dev/odigos/assets/48925621/1be53d76-c829-4246-a95e-72bf9ce54413)
![image](https://github.com/keyval-dev/odigos/assets/48925621/7e50e071-60b3-4e7d-bf06-260ba30ec498)

**Comment by SzymonSt** [comment]
I can have a look once it is labeled and confirmed by maintainers.

**Comment by edeNFed** [comment]
@SzymonSt nice catch. Would you be able to work on fixing this?

**Comment by SzymonSt** [comment]
yes I will
