### ISSUE TITLE
Add new destination: Elastic Observability

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#528]
**Destination name**: [Elastic Observability](https://www.elastic.co/observability)
**Support OpenTelemetry format**: yes, see: https://www.elastic.co/guide/en/apm/guide/8.10/open-telemetry-direct.html#connect-open-telemetry-collector
**Supported signals**: traces, metrics, logs

**Comment by SzymonSt** [comment]
I will have a look.

**Comment by yuvanmytri** [comment]
Hi @SzymonSt - seems like with latest version of odigos Elastic APM does not seems to work, Collector config does not seems to be generated. Could you please help?
