### ISSUE TITLE
Add new destination: HyperDX

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#529]
Destination name: [HyperDX](https://www.hyperdx.io/)
Support OpenTelemetry format: yes, see: https://www.hyperdx.io/docs/install/opentelemetry
Supported signals: traces, metrics, logs

**Comment by aditya-adhane** [comment]
@edeNFed Can I work on this.

**Comment by SzymonSt** [comment]
Hello @aditya-adhane If you need any help is needed let me know.

**Comment by SzymonSt** [comment]
@edeNFed you can assign it to me
