### ISSUE TITLE
Add new destination: Highlight.io

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#530]
**Destination name**: [Highlight.io](https://www.highlight.io)
**Support OpenTelemetry format**: yes, see: https://www.highlight.io/docs/getting-started/backend-logging/file
**Supported signals**: logs

**Comment by NewtonFernandis** [comment]
@edeNFed I will work on this

**Comment by SzymonSt** [comment]
Hello @NewtonFernandis  If you need any help is needed let me know.
