### ISSUE TITLE
Duplicate links to docs intro page

### ISSUE THREAD

**Issue by justinsteele** [keyval-dev/odigos#54]
**Describe the bug**
Minor duplication in README - "Getting Started Guide", "Documentation", and "quickstart guide" all end up at https://docs.odigos.io/intro as it is the default docs page

**To Reproduce**
1. Go to https://github.com/keyval-dev/odigos#readme
2. Click on any of the 3 links mentioned ("Getting Started Guide", "Documentation", and "quickstart guide")

**Expected behavior**
Links lead to different information/user flows, or links are deduplicated and have consistent labeling.

**Comment by edeNFed** [comment]
+1 
The current README is not so great and needs improvement.
