### ISSUE TITLE
CLI: odigos install return success even if DaemonSet pods are not up

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#541]
When installing odigos via the CLI by running `odigos install` the cli reports installation successful even if Odiglet (the deployed DaemonSet) is not running. Kubernetes may refuse to start the pods of Odiglet (for example: if there is a PodSecurityPolicy that blocks `hostPID`).

`arePodsReady` function should also check that for any DaemonSet in the `ns` namespace the number of running pods equal to the number of desired and is bigger than 1.
https://github.com/keyval-dev/odigos/blob/2f7d45c9a2deb1751bab3e120fe86a1ea1fdc7f5/cli/cmd/install.go#L86

**Comment by blumamir** [comment]
> I can take it

Thanks @SzymonSt
