### ISSUE TITLE
Remove unnecessary logs from frontend API server

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#542]
https://github.com/keyval-dev/odigos/blob/2f7d45c9a2deb1751bab3e120fe86a1ea1fdc7f5/frontend/endpoints/namespaces.go#L96

Is happening a lot and does not indicate an error. We should either log it in a higher debug level or just remove this line.

**Comment by Rhythm-08** [comment]
Hello I would like to solve this issue
