### ISSUE TITLE
Copy documentation from odigos-docs repository to docs directory in this repo

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#544]
We would like to have the documentation in the same repository as Odigos' code.
Currently, all documentation files are stored at: https://github.com/keyval-dev/odigos-docs/
We should create a new subdirectory called `docs` and put everything there

**Comment by dollarboysushil** [comment]
will you assign this to me?

**Comment by dollarboysushil** [comment]
@edeNFed  done , would you mind reviewing the PR
