### ISSUE TITLE
Generate supported destination table according to the destination YAML files

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#549]
Currently, our README.md contains a hard-coded table of all the destinations supported by Odigos.
The same data is available in `destination/data/*.yaml` files.
The destination table could be automatically generated from the YAML files, making it always in sync with the destinations actually supported.

**Comment by ShatilKhan** [comment]
Interested, please assign

**Comment by blumamir** [comment]
Thanks @ShatilKhan
