### ISSUE TITLE
Opt-out installation leaves deployments in error state because uninstallation is a work in progress

### ISSUE THREAD

**Issue by arnaudaz** [keyval-dev/odigos#55]
**Describe the bug**
While installing in a cluster with existing deployments, installing and using the opt-out option for odigos leads to a situation where cluster services end up in crashloopbackoff with no easy way to fix other than reapplying all deployment manifests.

I understand that the documentation states uninstalling is a work in progress, but the mutation of deployments and statefulsets leaves them in a bad state after uninstall, and users without gitops or similar deployment methods will face challenges in fixing their deployments. A workaround and a prominent warning should be displayed on this repo until there is a clean uninstall path.

**To Reproduce**
1. Install Odigos
2. In UI setup, go through the opt-out option flow for setup
3. Setup a backend (optional)
4. wait for services to be instrumented
5. disable services that are enabled for instrumentation in odigos UI
6. helm uninstall odigos
7. Pods that start up that were instrumented still have odigos sidecar, configurations, volumemount, and command changes. These pods may also be in crashloop/containerconfigcreateerror states.

**Expected behavior**
Changes by odigos to deployments should be reverted when odigos is disabled and uninstalled.

**Comment by edeNFed** [comment]
Thank you for filling the issue @arnaudaz 
We are planning a change in Odigos to make installation/uninstallation much easier.
In the upcoming version, we will use a custom CSI driver instead of modifying Deployments / StatefulSets for adding the instrumentation. This should keep the YAMLs untouched.

**Comment by edeNFed** [comment]
@arnaudaz This is now resolved by moving to instrumentation using [Kubernetes device plugin](https://keyval.dev/instrumentation-as-resource/).
Happy to hear your feedback
