### ISSUE TITLE
Update CONTRIBUTING.md file to explain how to develop Odigos locally

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#553]
The main steps involved when debugging Odigos locally:
- Use Kind kubernetes cluster
- Build custom images of Odigos and load them to Kind via:
```bash
 TAG=<CURRENT-ODIGOS-VERSION> make build-images load-to-kind
```
- Make sure TAG is similar to the Odgiso version output: `odigos version`
- Restart all pods in `odigos-system` namespace:
```bash
kubectl delete pods --all -n odigos-system
```

**Comment by idrismusa4** [comment]
Please assign to me

**Comment by idrismusa4** [comment]
Thanks 
To clarify I'm adding another link to "how to develop locally" in the md file right?

**Comment by edeNFed** [comment]
Yes, adding another section that describes how to develop locally sounds good.

**Comment by idrismusa4** [comment]
Thanks for the clarification I'll get right to it
