### ISSUE TITLE
Add relevant texts to odigos cli help

### ISSUE THREAD

**Issue by blumamir** [keyval-dev/odigos#554]
When running `$odigos --help`, the following output is generated:

```
A longer description that spans multiple lines and likely contains
examples and usage of using your application. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.

Usage:
  odigos [command]

Available Commands:
  add         A brief description of your command
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  install     Install Odigos
  ui          Start the Odigos UI
  uninstall   A brief description of your command
  version     A brief description of your command

Flags:
  -h, --help                help for odigos
      --kubeconfig string   (optional) absolute path to the kubeconfig file (default "/Users/amirblum/.kube/config")

Use "odigos [command] --help" for more information about a command.
```

Odigos should replace all the default texts such as "A brief description of your command" with meaningful information

**Comment by NotTheRightGuy** [comment]
Hey I think I can help with this. Can you assign this issue to me?

**Comment by blumamir** [comment]
> Can you just tell me one thing i have to update and add more information about specific commands and arguments in the help itself right.

You are right.

You will need to review the cli commands [here](https://github.com/keyval-dev/odigos/tree/main/cli/cmd) and for each command, make sure the text is meaningful. If not, it should be replaced to meaningful text.

Notice that since the PR was opened few changes were made. I think the places left to fix are [here](https://github.com/keyval-dev/odigos/blob/d5274bd8dca637c9915dad1765bd6a831a8fa8da/cli/cmd/observability.go#L23) and [here](https://github.com/keyval-dev/odigos/blob/d5274bd8dca637c9915dad1765bd6a831a8fa8da/cli/cmd/root.go#L14)
