### ISSUE TITLE
Build ARM docker images on dedicated ARM-based github runners

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#555]
GitHub just announced new ARM-based runners:
https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

Currently, the majority of the build time is spent on building ARM images on x64 runners.
Moving to building the ARM images on ARM runners should make our build time much faster.

**Comment by CyberHippo** [comment]
Hi @edeNFed I could help for this issue. I'll work on a PR.
