### ISSUE TITLE
Upload Odigos CLI to Chocolatey package manager

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#559]
Use goreleaser ability to publish the CLI to Chocolatey:
https://goreleaser.com/customization/chocolatey/?h=chocolatey

This should be useful for Windows users of the CLI.

**Comment by HeetVekariya** [comment]
I would like to work on this issue,
But can you give more information what exactly have to do

**Comment by edeNFed** [comment]
@HeetVekariya here are the goreleaser docs on this topic: https://goreleaser.com/customization/chocolatey/?h=chocolatey

**Comment by HeetVekariya** [comment]
- @edeNFed I have already assigned with 3 issues of Odigos itself.

- So I it think that this issue should be open for other contributors.

- I will finish that issues first, and if no one is assigned with this issue then I will work on this issue
