### ISSUE TITLE
Implement Reusable Pie Chart Component Using JavaScript and Styled Components

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#560]
We would like to add a Pie Chart component to our project, implemented using JavaScript and Styled Components, to visualize data in a more engaging and informative way.

<img width="540" alt="image" src="https://github.com/keyval-dev/odigos/assets/138359965/c63c3bc0-3240-4808-9f40-f9c32167b1f8">

**Example Usage**
Here's an example of how the Pie Chart component could be used within our project:

import React from 'react';
import PieChart from './PieChart';

const data = [
  { label: 'Logs', value: 30, strokeColor: '#000'},
  { label: 'Metrics', value: 40,strokeColor: 'red'},
  { label: 'Traces', value: 20 },
];

function App() {
  return (
    <div>
      <h1>Distribution</h1>
      <PieChart data={data} />
    </div>
  );
}

export default App;

**Comment by ronisarkarexe** [comment]
@alonkeyval Are you utilizing any npm packages or are you solely using plain JavaScript?

**Comment by alonkeyval** [comment]
@ronisarkarexe  We do not use a third-party lib at the moment but we do not rule out the possibility of it for the use of the graphs

**Comment by ronisarkarexe** [comment]
@alonkeyval can you assign me

**Comment by alonkeyval** [comment]
Assigned @ronisarkarexe
