### ISSUE TITLE
Use custom collector in odigos repo instead of forked collector

### ISSUE THREAD

**Issue by blumamir** [keyval-dev/odigos#561]
Odgios adds an opentelemetry collector for each pod as a daemonset [here](https://github.com/keyval-dev/odigos/blob/02639256a750cfa8e0e7555954af046fc8140c23/autoscaler/controllers/datacollection/daemonset.go#L145).

The image name being used [is](https://github.com/keyval-dev/odigos/blob/02639256a750cfa8e0e7555954af046fc8140c23/autoscaler/controllers/datacollection/daemonset.go#L27C2-L27C16) and the repo can be found [here](https://github.com/keyval-dev/opentelemetry-collector-contrib/tree/main).

The reason a forked collector is used, is because odigos needs [a custom processor](https://github.com/keyval-dev/opentelemetry-collector-contrib/tree/main/processor/odigosresourcenameprocessor) `odigosresourcenameprocessor`.

Using a forked repo, is not opentelemetry best practice, as it requires a separate repo, complex merges, and managing the deployment. We should convert to using [ocb](https://opentelemetry.io/docs/collector/custom-collector/), by moving the custom processor code into this repo and creating a [builder-manifest-file](https://opentelemetry.io/docs/collector/custom-collector/#step-2---create-a-builder-manifest-file) to build and distribute the collector image.

**Comment by kousikmitra** [comment]
@blumamir I can work on this, for the custom collector do we want all the components under otel-contrib? or is there specific components that we need?

**Comment by blumamir** [comment]
Thanks @kousikmitra ,

That would be awsome. If you need to chat about it, please reach out in [odigos slack](https://join.slack.com/t/odigos/shared_invite/zt-24u91yknm-0fLXu6qnqYfNHS_GSUgTJw)

We could add just the processors and exporters we actually use in odigos. You can find these in the code. Let me know if you need more info 🙏
