### ISSUE TITLE
remove empty "skill" cli command

### ISSUE THREAD

**Issue by blumamir** [keyval-dev/odigos#562]
odigos cli includes a `skill` command that does nothing [here](https://github.com/keyval-dev/odigos/blob/main/cli/cmd/skill.go).

It can be safely removed

**Comment by JuanGuerrero09** [comment]
Hi!, can you assign me this issue?

**Comment by blumamir** [comment]
Thanks @JuanGuerrero09

**Comment by blumamir** [comment]
merged with #590
