### ISSUE TITLE
Notify Odigos slack channel when new version is released

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#563]
We would like to notify all Odigos users automatically via slack when a new version of Odigos is released.

Add to GitHub Action workflow on tag: invoke slack webhook `ODIGOS_SLACK_WEBHOOK` stored as repository secret.
Add the relevant changelog to the announcement message.

**Comment by yagueto** [comment]
Hi! I'd like to take up this issue, can I be assigned?
