### ISSUE TITLE
Implement Reusable Segmented Controls Using TypeScript and Styled Components

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#564]
We would like to introduce a reusable Segmented Controls component to our project, implemented using JavaScript and Styled Components. This component will provide users with an intuitive way to make selections or switch between options.

<img width="692" alt="image" src="https://github.com/keyval-dev/odigos/assets/138359965/7802685f-b5a1-49f1-8488-b8c3fa6cd86c">

**Example Usage**
Here's an example of how the Segmented Controls component could be used within our project:

import React, { useState } from 'react';
import SegmentedControls from './SegmentedControls';

function App() {
  const [selectedOption, setSelectedOption] = useState('Option 1');

  const handleOptionChange = (newOption) => {
    setSelectedOption(newOption);
    // Trigger further actions based on the selected option.
  };

  return (
    <div>
      <SegmentedControls
        options={['Option 1', 'Option 2', 'Option 3']}
        selected={selectedOption}
        onChange={handleOptionChange}
      />
      <p>Selected Option: {selectedOption}</p>
    </div>
  );
}

export default App;

**Comment by VadimDez** [comment]
@alonkeyval Could you please assign it to me? I would like to give it a try

**Comment by alonkeyval** [comment]
@VadimDez sure! thanks for the help
