### ISSUE TITLE
Implement Reusable useKeyDown Hook for Keyboard Event Handling

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#568]
Currently, keyboard event handling within our components involves adding a window.addEventListener('keypress', handleKeyPress) directly inside each component where keyboard input is required. This approach can lead to code duplication, reduced maintainability, and potential issues with event listeners accumulating and not being cleaned up correctly. To address these concerns, we need to create a reusable useKeyDown hook that can be easily used across components.

**Proposed Solution**
We propose implementing a useKeyDown hook that encapsulates the logic for registering and handling keyboard events. This hook should provide a clean and standardized way for components to respond to key presses without the need to manage event listeners individually.

<img width="557" alt="image" src="https://github.com/keyval-dev/odigos/assets/138359965/cf51f624-832a-4629-bc45-983dd87e752b">

**Comment by Kritik-J** [comment]
I would like to work on it. Please assign this to me

**Comment by utsavvvv** [comment]
I want to work on this task. Please assign it to me sir @alonkeyval

**Comment by alonkeyval** [comment]
thanks for the help guys @utsavvvv  @Kritik-J
