### ISSUE TITLE
Request Removal of Tailwind CSS from Project Dependencies

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#571]
We are requesting the removal of Tailwind CSS from our project's dependencies. While Tailwind CSS is a powerful utility-first CSS framework, we have decided to move away from it for various reasons, and we no longer wish to maintain it as part of our project

**Comment by ankur12-1610** [comment]
@alonkeyval, I would to work on this issue!

**Comment by alonkeyval** [comment]
@ankur12-1610  assigned :)

**Comment by Kritika30032002** [comment]
Please assign me this issue.
