### ISSUE TITLE
Use markdown linter for higher quality readmes

### ISSUE THREAD

**Issue by blumamir** [keyval-dev/odigos#574]
[Similar to opentelemetry repos](https://github.com/open-telemetry/opentelemetry-go/blob/main/.github/workflows/markdown.yml), we can add markdown linter steps to the CI to make sure the READMEs apply best practices.

I think we can use opentelemetry workflow as is:
https://github.com/open-telemetry/opentelemetry-go/blob/main/.github/workflows/markdown.yml

**Comment by ankur12-1610** [comment]
Hi, can work on it?
