### ISSUE TITLE
 Request Addition of Reusable Slider Component Using TypeScript and Styled Components

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#575]
We are requesting the implementation of a reusable Slider component for our project. This Slider component should be built using TypeScript and Styled Components, providing us with a flexible and customizable way to capture user input for selecting values within a specified range.

<img width="419" alt="image" src="https://github.com/keyval-dev/odigos/assets/138359965/bb797d7a-5212-44f7-bbbf-2bfa17cb7980">

**Additional Information**

- Our project is built using TypeScript and Styled Components, so it's important that the Slider component is compatible with these technologies.
- Any dependencies that need to be added to our project should be clearly documented.
- We prioritize clean, maintainable code, so please ensure that the code adheres to best practices and can be easily maintained.

**Comment by Krishnakalani111** [comment]
please assign this issue to me, and if you do let me know where it should lie in the folder structure

**Comment by alonkeyval** [comment]
@Krishnakalani111 please add this to the design system folder

**Comment by Kritika30032002** [comment]
Please assign me this issue.

**Comment by alonkeyval** [comment]
Thanks @Kritika30032002

**Comment by Kritika30032002** [comment]
hey!
can u tell me the folder in which component should be there

**Comment by alonkeyval** [comment]
@Kritika30032002 design.system folder

**Comment by chinmay7016** [comment]
hey @alonkeyval pls assign this issue to me.
