### ISSUE TITLE
Removal of Lottie from Codebase

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#577]
We are requesting the removal of Lottie from our codebase. Lottie is currently integrated into our project for animations, but we have decided to remove it for various reasons, and we no longer wish to maintain it as part of our project.

**Comment by utsavvvv** [comment]
I want to work on this task. Please assign it to me sir @alonkeyval

**Comment by blumamir** [comment]
Thanks @utsavvvv 🙏
