### ISSUE TITLE
remove unused dependencies from nodejs instrumentation agent

### ISSUE THREAD

**Issue by blumamir** [keyval-dev/odigos#578]
[Odigos nodejs agent](https://github.com/keyval-dev/odigos/blob/main/odiglet/agents/nodejs/package.json) includes some unused dependencies in `package.json`.

Since the agent does not collect metrics at the moment, I think these are redundant:
- "@opentelemetry/sdk-metrics"
- "@opentelemetry/exporter-metrics-otlp-grpc"
- "@opentelemetry/exporter-prometheus"

@edeNFed - WDYT?

**Comment by edeNFed** [comment]
👍🏻 sounds like a great idea

**Comment by Krishnakalani111** [comment]
i want to contribute, please assign this to me
