### ISSUE TITLE
Feature Request: Implement Dark Mode

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#579]
We would like to request the implementation of a Dark Mode feature in our project. Dark mode is a highly requested user interface enhancement that provides users with the option to switch between a light and dark color scheme, improving usability in low-light environments and reducing eye strain.

**Description**
Dark mode has become a standard feature in many applications and websites. Implementing this feature in our project can provide the following benefits:

- Improved user experience for users who prefer darker themes.
- Accessibility improvements for users with light sensitivity.
- Energy savings for users on OLED or AMOLED screens.
- Alignment with modern design trends.

**Comment by alonkeyval** [comment]
Thanks @mrswastik-robot

**Comment by AviGawande** [comment]
want to work on this topic ,could you please assign it to me.

**Comment by alonkeyval** [comment]
@AviGawande  assigned!

**Comment by VBPMP** [comment]
please, Kindly Assign me this issue
