### ISSUE TITLE
 Refactor: Cleanup and Optimize CSS

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#580]
We are requesting a comprehensive CSS cleanup and optimization effort in our project. Over time, the CSS codebase has become complex, and we believe that it's essential to streamline and optimize the styles to improve performance, maintainability, and overall code quality.

**Description**
The current CSS code may include unused styles, redundancy, and suboptimal practices that can impact the project negatively. A thorough CSS cleanup and optimization will result in the following benefits:

- Improved page load times by reducing the CSS file size.
- Enhanced maintainability, making it easier to update and manage styles.
- Better organization and structure of stylesheets.
- Alignment with best practices for modern CSS development.

**Comment by utsavvvv** [comment]
I want to work on this task , Please assign it to me sie @alonkeyval

**Comment by utsavvvv** [comment]
I want to work on  this task. Please assign it to me sir @alonkeyval

**Comment by Kritika30032002** [comment]
Please assign me this issue.

**Comment by Aviraltech** [comment]
Hey, I would like to work on this.

**Comment by alonkeyval** [comment]
@utsavvvv @Aviraltech @Kritika30032002, any updates guys?
