### ISSUE TITLE
Performance Degradation on Page Load

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#581]
Users have reported a noticeable performance degradation during the initial page load of our application. This issue impacts the user experience, and we need to investigate and resolve it promptly.

**Description**
The performance degradation during page load may manifest as slower loading times, excessive network requests, or high CPU and memory usage. This issue can deter users from using our application and must be addressed to ensure optimal performance.

**Comment by fadkeabhi** [comment]
I would like to work on this issue. Assign it to me.
