### ISSUE TITLE
Refactor: Split Monolithic Components into Smaller Ones

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#583]
We are requesting a refactoring effort to split monolithic components in our project into smaller, more manageable components. This refactoring will help improve code maintainability, readability, and reusability while following best practices for componentization.

target component: create.connection.form.tsx

**Comment by Paul-Annay** [comment]
Hey there, I would like to work on this!

**Comment by alonkeyval** [comment]
Assigned @Paul-Annay

**Comment by Paul-Annay** [comment]
![image](https://github.com/keyval-dev/odigos/assets/84911232/1829e13d-4b14-460b-ac57-f25ca4ecf5b7)

Hey there, I have refactored the [form.tsx](https://github.com/keyval-dev/odigos/blob/main/frontend/webapp/components/setup/connection/create.connection.form/create.connection.form.tsx) component by separating the code into 3 smaller components. The image shows the folder structure. Is there any particular naming convention or folder-structure pattern that you would like me to follow. I went through the [CONTRIBUTION.md](https://github.com/keyval-dev/odigos/blob/main/CONTRIBUTING.md) but did not find any specific guidelines regarding this.

Additionally I have tried to run the NextJs front-end part locally on my device by installing the node dependencies but the UI doesn't seem to render. I figured it has something to do with the api-end point which was suppose to run on [http://localhost:8085/api/config ](http://localhost:8085/api/config ). Could you kindly suggest how I should proceed with running this locally?

**Comment by alonkeyval** [comment]
Hi @Paul-Annay, thanks for the help!
Can you provide an explanation of the steps you took to operate the user interface?

**Comment by Paul-Annay** [comment]
Sure @alonkeyval 
Step 1: I navigated to the [frontend/webapp](https://github.com/keyval-dev/odigos/tree/main/frontend/webapp) directory
Step 2: Used the command `npm install --legary-peer-deps` to install the node dependencies
Step 3: Used `npm run dev` to start the development server.
![image](https://github.com/keyval-dev/odigos/assets/84911232/5e14770c-3016-4f7c-a997-6942606ddef1)


The Development Server is launched successfully, but the UI rendered in the Browser is Empty.
![image](https://github.com/keyval-dev/odigos/assets/84911232/331d6837-2910-4b13-89dc-39096628d41b)

I am on a windows 11 pc and the browser I am using is Brave (Chromium Based).

**Comment by alonkeyval** [comment]
@Paul-Annay did you build odigos-backend?

**Comment by Paul-Annay** [comment]
@alonkeyval no sir, could you kindly provide instructions on how to build the backend?

**Comment by Paul-Annay** [comment]
@alonkeyval I have tried to run the Dockerfile in the root directory along with the Dockerfile in the frontend directory but apparently I run into errors. Could you kindly tell me how I will be able to run the backend of the application locally?

**Comment by alonkeyval** [comment]
@Paul-Annay  please follow the instructions [here](https://docs.odigos.io/intro), let me know if you need more help
