### ISSUE TITLE
Add CLI compilation check on PRs

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#589]
We should add a check for compiling the CLI project (located at `/cli`) during pull requests.
This will make sure we will not break compilation when merging (see #588)

**Comment by kailashchoudhary11** [comment]
Hey, I would like to work on this.

**Comment by edeNFed** [comment]
Hi @kailashchoudhary11 just following up.
Let me know if you need some help.

**Comment by kailashchoudhary11** [comment]
> Hi @kailashchoudhary11 just following up. Let me know if you need some help.

Hi, I was a bit busy will start working on it tonight and will let you know.

**Comment by edeNFed** [comment]
Hi @kailashchoudhary11 any update?
