### ISSUE TITLE
Social Media Icons in footer are not centered perfectly.

### ISSUE THREAD

**Issue by git-ritesh** [keyval-dev/odigos#592]
- **Social Media Integration Icons in the footer are not centered inside their container.**

  ![links-not-centered](https://github.com/keyval-dev/odigos/assets/96147001/cd5d5c35-f1b0-45ac-b2b7-1a048f58488f)

- **In Mobile view of width:375px one icon moves below which gives a bad User Experience.**
  
  ![bad-ui](https://github.com/keyval-dev/odigos/assets/96147001/c1c3358c-8c87-4f00-ad08-0621a3dd4871)

**Laptop(Rog Strix G15 G5131H) :**
 - OS: Linux Mint
 - Browser : Firefox Developer Edition 
 - Version : 119.0b4 (64-bit)

**Mobile (Realme Narzo 30A) :**
 - Device: Realme Narzo 30A
 - OS: Android 11
 - Browser : Google Chrome
 - Version : 117.0.5
```[tasklist]
### Tasks
```

**Comment by git-ritesh** [comment]
I'm not the owner of this repo

**Comment by HridoyHazard** [comment]
> I'm not the owner of this repo

hi i don't even see any social media icons? where did you see it?

**Comment by git-ritesh** [comment]
@HridoyHazard when i opened their website [odigos.io](https://odigos.io/) I saw that but now the whole homepage has been modified.
