### ISSUE TITLE
Describe sections in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ankur12-1610** [keyval-dev/odigos#593]
**Is your feature request related to a problem? Please describe.**
https://github.com/keyval-dev/odigos/blob/main/CONTRIBUTING.md#pull-request-lifecycle
https://github.com/keyval-dev/odigos/blob/main/CONTRIBUTING.md#development-environment-setup
https://github.com/keyval-dev/odigos/blob/main/CONTRIBUTING.md#sign-your-commits
https://github.com/keyval-dev/odigos/blob/main/CONTRIBUTING.md#pull-request-checklist

They are not yet described. Do we have a content for the same?

**Comment by HeetVekariya** [comment]
@ankur12-1610 Can you please elaborate more about the issue.

**Comment by blumamir** [comment]
This is fixed in #646
