### ISSUE TITLE
Odigos UI bind to different port if port 3000 already taken

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#599]
when launching Odigos UI via`odigos ui` we are trying to listen on port 3000, if this port is taken by another application we should try other ports.

I think trying 3001,3002,3003 before giving up sounds reasonable.

**Comment by rahul0x00** [comment]
Hi, I'd like to work on this issue, could you assign it to me?

**Comment by rahul0x00** [comment]
Hi, I've made the necessary code changes and made the PR, but I encountered difficulties setting up the project on my server. I believe the changes should work as intended ,let me know if it doesn't work

**Comment by rahul0x00** [comment]
sorry about the mess
