### ISSUE TITLE
Social Media section in the footer 

### ISSUE THREAD

**Issue by HridoyHazard** [keyval-dev/odigos#603]
**Is your feature request related to a problem? Please describe.**
no it's not related to any problem.

**Describe the solution you'd like**
i would like to add social media icons in the footer which will make the website looks complete. 

**Describe alternatives you've considered**
N/A
**Additional context**

**Comment by HridoyHazard** [comment]
kindly assign this to me

**Comment by Kritika30032002** [comment]
kindly assign this to me
