### ISSUE TITLE
Odigos uninstall console output bug

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#614]
When running `odigos uninstall` the checkmarks of the steps 
`Rolling back odigos changes to pods` and `Rolling back odigos changes to namespaces` are misplaced.

See the following image:
![Screenshot 2023-10-08 at 3 50 51 PM](https://github.com/keyval-dev/odigos/assets/5587419/f7552dd1-8c79-4b22-8f45-1a18ca6d68c4)

**Comment by ankur12-1610** [comment]
Hey, I would like to work on this issue.

**Comment by ankur12-1610** [comment]
Hi @edeNFed, what should be the correct order of the checkmarks?

**Comment by HeetVekariya** [comment]
I would like to work on this issue as this is good first issue, can you please assign it to me.

**Comment by edeNFed** [comment]
The checkmarks should be in the same line of the current operation.
So this should be fixed to:
```
Rolling back odigos changes to pods ..... V
Rolling back odigos changes to namespaces ... V
```

**Comment by HeetVekariya** [comment]
@edeNFed Please look into it.

- This is the current code:
![image](https://github.com/keyval-dev/odigos/assets/91054457/d81842d1-b29a-4fc2-8e95-8eaeffa11823)


- Changes made to get the desired output:
   - Remove "\n" from end of the ```log.print``` to print the tic mark in the same line
   - Added l.success() after ```log.Print("Rolling back odigos changes to pods")```
   
 - I have to codes:

(A)
![image](https://github.com/keyval-dev/odigos/assets/91054457/92812705-0e6a-44dd-9020-99e8ebfac318)

  (B) 
  ![image](https://github.com/keyval-dev/odigos/assets/91054457/0cf22187-c622-4cc0-9324-1268a997c42b)


- If my solution is correct, please let me know which code you want to continue with from above two

**Comment by HeetVekariya** [comment]
@ankur12-1610 I think the current is assigned to me, so PR should be submitted by me as written in the contributing.md

**Comment by HeetVekariya** [comment]
@edeNFed I have submitted the PR, can please review it and comment if change needed.

**Comment by HeetVekariya** [comment]
@edeNFed Thank you for merging, close this issue as completed.
