### ISSUE TITLE
Links not working in CONTRIBUTING.md

### ISSUE THREAD

**Issue by shelar1423** [keyval-dev/odigos#615]
**Describe the bug**
few links are not working in CONTRIBUTING.MD
- [Pull Request Lifecycle]
- [Development Environment Setup]
- [Sign Your Commits]
- [Pull Request Checklist]

![image](https://github.com/keyval-dev/odigos/assets/82649533/40df5473-136b-465f-9701-9f9a92ab9677)

-would like to work on this issue

**Comment by shelar1423** [comment]
@edeNFed i would like to know the content to fix this and work on this, can you assign this issue to me

**Comment by HeetVekariya** [comment]
I would like to work on this issue as this looks good first issue, can you please assign it to me.

**Comment by nrhitik** [comment]
I would like to work on this issue. could you please assign me this issue.

**Comment by shelar1423** [comment]
Hey @blumamir thank you for assigning me the issue I want to know what links are to be put there ? Or any text is to be added ?

**Comment by blumamir** [comment]
I don't have any text to add at the moment, but we can do it also in later PRs. I suggest just removing the dead links now

**Comment by shelar1423** [comment]
sure @blumamir

**Comment by blumamir** [comment]
fixed
