### ISSUE TITLE
The pod of the demo app is crashed when instrumentation is enabled

### ISSUE THREAD

**Issue by liurui-1** [keyval-dev/odigos#62]
**Describe the bug**
The pod of the demo app is crashed when instrumentation is enabled.

**To Reproduce**
1. Run command according to the doc:
kubectl apply -f https://raw.githubusercontent.com/keyval-dev/microservices-demo/master/release/kubernetes-manifests.yaml

2. Install Odigos
helm repo add odigos https://keyval-dev.github.io/odigos-charts/
helm install my-odigos odigos/odigos --namespace odigos-system --create-namespace

3. Enable instrumentation with the UI

4. Find pod are crashed
kubectl get pod -n default

**Expected behavior**
The pod should not be crashed

**Screenshots**
The following screenshot is after I enable instrumentation for frontend pod:
![image](https://user-images.githubusercontent.com/3861860/215728530-ecb0f70f-04eb-4a38-8f99-665e4aeefd6b.png)

**Environment:**
 - OS: Ubuntu 18.04.6 LTS
 -  kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
 - Browser Firefox 109.0

**Additional context**
It seems the problem is caused by some compatibility issue of Golang packages:
```
kubectl logs -f frontend-54d7ddf7f4-54tcn -p -c server-instrumentation
... ...
{"level":"info","ts":1675158604.7114024,"caller":"grpc/probe.go:213","msg":"closing gRPC instrumentor"}
{"level":"info","ts":1675158604.7114253,"caller":"server/probe.go:223","msg":"closing gRPC server instrumentor"}
{"level":"info","ts":1675158604.7114346,"caller":"server/probe.go:179","msg":"closing net/http instrumentor"}
{"level":"info","ts":1675158604.7114527,"caller":"mux/probe.go:179","msg":"closing gorilla/mux instrumentor"}
{"level":"error","ts":1675158604.7114713,"caller":"cli/main.go:79","msg":"error while running instrumentors","error":"field UprobeClientConnInvoke: program uprobe_ClientConn_Invoke: map .rodata: map create: read- and write-only maps not supported (requires >= v5.2)","stacktrace":"main.main\n\t/app/cli/main.go:79\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

**Comment by eugercek** [comment]
I couldn't reproduce:
```
NAME                                                 READY   STATUS                       RESTARTS      AGE
adservice-6f67d85774-bhgrk                           1/1     Running                      0             2m25s
cartservice-58fdffdc4b-kr95k                         1/1     Running                      0             2m29s
checkoutservice-57f7bbd798-99rbx                     2/2     Running                      0             2m26s
currencyservice-756d768f4f-jqpd7                     1/1     Running                      0             2m25s
emailservice-695c7b5c64-48fbv                        1/1     Running                      0             2m29s
frontend-895684f88-mwjnh                             2/2     Running                      0             2m26s
paymentservice-6798cc4d58-kjld7                      1/1     Running                      0             2m25s
productcatalogservice-584fbb9dcc-bvzmw               2/2     Running                      0             2m29s
recommendationservice-d778cf9d5-j4d54                1/1     Running                      0             2m29s
redis-cart-5d45978b94-kjhtf                          1/1     Running                      0             10m
shippingservice-68b67fb65c-rjc28                     2/2     Running                      0             2m26s
```

I used Prometheus as destination, what was your destination? Also I'm not sure but `k describe pods frontend-54d7ddf7f4-54tcn` could be valuable for debugging.

---
OS: macOS Ventura 13.1
kubectl: 
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```
kubernetes: `kind v0.17.0 go1.19.3 darwin/amd64`

**Comment by liurui-1** [comment]
@eugercek I used Jaeger as the destination.

**Comment by liurui-1** [comment]
This time I completed reinstalled the system with only one destination of Prometheus (enabled remote write). After instrumentation, the app pods began to crash. Without instrumentation, the apps are running well.
```
root@overlap1:~# kubectl get pod
NAME                                     READY   STATUS             RESTARTS      AGE
adservice-5ddf5cdd4d-cn24x               1/1     Running            0             114s
cartservice-5987d8cc4b-4bctt             1/1     Running            0             113s
checkoutservice-65778b9944-gqm89         1/2     NotReady           4 (62s ago)   114s
currencyservice-84dddf765f-mdng8         1/1     Running            0             113s
emailservice-8645779d8b-ht6s5            1/1     Running            0             113s
frontend-54d7ddf7f4-8n4kh                1/2     CrashLoopBackOff   4 (13s ago)   113s
paymentservice-66bc468848-9jnhh          1/1     Running            0             113s
productcatalogservice-6bdd6547f9-k5cx9   1/2     NotReady           4 (54s ago)   114s
recommendationservice-865dbfdf6c-bd8g8   1/1     Running            0             114s
redis-cart-548dfd74d-96xzv               1/1     Running            0             3m52s
shippingservice-85f789758c-qzfm8         1/2     NotReady           4 (60s ago)   114s
root@overlap1:~# kubectl describe pod frontend-54d7ddf7f4-8n4kh
Name:             frontend-54d7ddf7f4-8n4kh
Namespace:        default
Priority:         0
Service Account:  default
Node:             overlap3/10.21.14.176
Start Time:       Fri, 03 Feb 2023 00:57:47 -0800
Labels:           app=frontend
                  pod-template-hash=54d7ddf7f4
Annotations:      cni.projectcalico.org/containerID: d063fa99d9bf0f90fb9f9c3edde206247a777c281e6a2618810be258787cf999
                  cni.projectcalico.org/podIP: 192.168.106.210/32
                  cni.projectcalico.org/podIPs: 192.168.106.210/32
                  sidecar.istio.io/rewriteAppHTTPProbers: true
Status:           Running
IP:               192.168.106.210
IPs:
  IP:           192.168.106.210
Controlled By:  ReplicaSet/frontend-54d7ddf7f4
Init Containers:
  odigos-init:
    Container ID:  containerd://3cf45eeca254d8798268dcdfc9ee953c3f7acaa389cf93efba7c5805f7ebd9bb
    Image:         ghcr.io/keyval-dev/odigos/init:v0.1.37
    Image ID:      ghcr.io/keyval-dev/odigos/init@sha256:a4a6dbd6b003db252be5793832b41ce0e3e30ed1cc9139590ed5875ddab8a7f5
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      -a
      /odigos-init/.
      /odigos/
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 03 Feb 2023 00:57:48 -0800
      Finished:     Fri, 03 Feb 2023 00:57:48 -0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /odigos from odigos (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9hnj2 (ro)
Containers:
  server:
    Container ID:  containerd://527e962f2f1cda32477766b93083b2e096c826359a41c8495a8ca545cf910eff
    Image:         edenfed/frontend:edae583@sha256:ae2bfbc2675e3c1411b36ccc10906a2af722c29218f2bbad176063e908d099a8
    Image ID:      docker.io/edenfed/frontend@sha256:ae2bfbc2675e3c1411b36ccc10906a2af722c29218f2bbad176063e908d099a8
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      /odigos/init
    Args:
      /frontend/server
    State:          Running
      Started:      Fri, 03 Feb 2023 00:57:50 -0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  64Mi
    Environment:
      PORT:                          8080
      PRODUCT_CATALOG_SERVICE_ADDR:  productcatalogservice:3550
      CURRENCY_SERVICE_ADDR:         currencyservice:7000
      CART_SERVICE_ADDR:             cartservice:7070
      RECOMMENDATION_SERVICE_ADDR:   recommendationservice:8080
      SHIPPING_SERVICE_ADDR:         shippingservice:50051
      CHECKOUT_SERVICE_ADDR:         checkoutservice:5050
      AD_SERVICE_ADDR:               adservice:9555
      ENV_PLATFORM:                  aws
      HOST_IP:                        (v1:status.hostIP)
      POD_NAME:                      frontend-54d7ddf7f4-8n4kh (v1:metadata.name)
      POD_NAMESPACE:                 default (v1:metadata.namespace)
    Mounts:
      /odigos from odigos (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9hnj2 (ro)
  server-instrumentation:
    Container ID:   containerd://a1da663bdf665d8fd52a820d76681d691a619173ac237cc863fb9564070620dd
    Image:          keyval/otel-go-agent:v0.6.1
    Image ID:       docker.io/keyval/otel-go-agent@sha256:7758bbd20c3e632dc9d7b3724e71607a137a6c97bc69e2d42a8886f11203573b
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 03 Feb 2023 00:59:25 -0800
      Finished:     Fri, 03 Feb 2023 00:59:27 -0800
    Ready:          False
    Restart Count:  4
    Environment:
      NODE_IP:                       (v1:status.hostIP)
      OTEL_EXPORTER_OTLP_ENDPOINT:  $(NODE_IP):4317
      OTEL_SERVICE_NAME:            frontend
      OTEL_TARGET_EXE:              /frontend/server
    Mounts:
      /sys/kernel/debug from kernel-debug (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9hnj2 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kernel-debug:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/kernel/debug
    HostPathType:
  odigos:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-9hnj2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  2m26s                default-scheduler  Successfully assigned default/frontend-54d7ddf7f4-8n4kh to overlap3
  Normal   Pulled     2m25s                kubelet            Container image "ghcr.io/keyval-dev/odigos/init:v0.1.37" already present on machine
  Normal   Created    2m25s                kubelet            Created container odigos-init
  Normal   Started    2m25s                kubelet            Started container odigos-init
  Normal   Pulled     2m24s                kubelet            Container image "edenfed/frontend:edae583@sha256:ae2bfbc2675e3c1411b36ccc10906a2af722c29218f2bbad176063e908d099a8" already present on machine
  Normal   Created    2m24s                kubelet            Created container server
  Normal   Started    2m23s                kubelet            Started container server
  Normal   Created    93s (x4 over 2m23s)  kubelet            Created container server-instrumentation
  Normal   Started    92s (x4 over 2m23s)  kubelet            Started container server-instrumentation
  Warning  BackOff    64s (x6 over 2m15s)  kubelet            Back-off restarting failed container server-instrumentation in pod frontend-54d7ddf7f4-8n4kh_default(70210906-656f-4edb-ae94-d48e36e63e5b)
  Normal   Pulled     49s (x5 over 2m23s)  kubelet            Container image "keyval/otel-go-agent:v0.6.1" already present on machine
```

**Comment by liurui-1** [comment]
My test env:
```
root@overlap1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
root@overlap1:~# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by noovertime7** [comment]
I also encountered a business container crash after enabling detection, with different error logs
Environment information.
CentOS Stream release 8
Kubernetes v1.21.5

Business container error log:
2023/02/07 02:12:06 failed to request allocation: bad status code: 500

instrumentation error log:

[root@k8s-master1 /]# kubectl logs -f -n tigera-operator tigera-operator-6c88dd4d87-6m5pr -c tigera-operator-instrumentation
{"level":"info","ts":1675735587.4068255,"caller":"cli/main.go:27","msg":"starting Go OpenTelemetry Agent ..."}
{"level":"info","ts":1675735587.4069169,"caller":"opentelemetry/controller.go:120","msg":"Establishing connection to OpenTelemetry collector ..."}
{"level":"info","ts":1675735589.4090347,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735591.4088633,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735593.4079084,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735595.4088101,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735597.408844,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735599.4085042,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735601.4083586,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735603.4075544,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735605.408892,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735607.4095123,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735609.4104497,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735611.4094179,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735613.407814,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735615.4089134,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735617.4080658,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735619.4095633,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735621.4085681,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735623.4091341,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735625.4089189,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735627.410032,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735629.409129,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735631.4086974,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735633.408319,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735635.4094505,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735637.4095912,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735639.408921,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735641.4113886,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735643.40783,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735645.4084597,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735647.4086082,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735649.4086783,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735651.408721,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735653.4079802,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735655.4088707,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735657.409031,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735659.408693,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735661.4087636,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735663.4078603,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735665.4095316,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735667.4085584,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735669.4085622,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735671.408757,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735673.408611,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735675.4087934,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735677.4089751,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735679.408681,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735681.4091122,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}
{"level":"info","ts":1675735683.407909,"caller":"process/discover.go:41","msg":"process not found yet, trying again soon","exe_path":"/usr/local/bin/operator"}

**Comment by adarshsrivastava11** [comment]
@eugercek  When the code is already instrumented, and we start Odigos, we get the following logs - 
`kubectl logs adservice-cb5c5b845-gqt2c`

```
Picked up JAVA_TOOL_OPTIONS: -javaagent:/odigos/java/javaagent.jar -Dotel.traces.sampler=always_on -Dotel.exporter.otlp.endpoint=http://172.18.0.2:4317
Error opening zip file or JAR manifest missing : /odigos/java/javaagent.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```
Moreover, all the crashing services seem to spin up a new pod. Can you kindly shed some light on why this behavior might be happening?
<img width="1213" alt="Screenshot 2023-04-06 at 12 35 49 AM" src="https://user-images.githubusercontent.com/14872767/230180090-067c8b79-d12d-483c-91ec-5ba4f65a6675.png">

**Comment by zhulong007** [comment]
> Moreover, all the crashing services seem to spin up a new pod. Can you kindly shed some light on why this behavior might be happening?

I have the same problem now, did you solve it?
