### ISSUE TITLE
Change the Twitter icon to X in the Documentation section.

### ISSUE THREAD

**Issue by pabitra0011** [keyval-dev/odigos#620]
**Is your feature request related to a problem? Please describe.**
"It must contain the X logo instead of the old Twitter logo."

**Describe the solution you'd like**
Just change old twitter logo to X logo.

**Additional context**
![image](https://github.com/keyval-dev/odigos/assets/94389910/b40640e0-2db6-4a1c-b3dc-91d04534162f)

**Comment by pabitra0011** [comment]
If you think this issue is valid please assing it to me.
Thank you.

**Comment by blumamir** [comment]
> If you think this issue is valid please assing it to me. Thank you.

Thanks @pabitra0011

**Comment by niranjan-kurhade** [comment]
Hey @blumamir, Is @pabitra0011 working on this issue? It's a long time. Can I make a really quick PR for this issue?
