### ISSUE TITLE
Hover Effect on Header Section

### ISSUE THREAD

**Issue by Its-Aman-Yadav** [keyval-dev/odigos#621]
When I hover over the top nav bar of the site, it doesn't feel much smooth cause there is no hover effect on them. It would be great if there was a hover effect on the top nav bar

I want to make a hover effect on the top nav bar

```[tasklist]
### Tasks
```

**Comment by Its-Aman-Yadav** [comment]
Kindly assign this issue to me, to get started

**Comment by AniketP04** [comment]
I am interested to take this  issue. Please assign me this issue.

**Comment by abhinavtyagi88** [comment]
I want make this awesome with a special effect according to theme that's why I would like to work on this

**Comment by Kritika30032002** [comment]
Please assign me this issue.

**Comment by atharvak86** [comment]
I would like to fix this issue, leave it to me .

**Comment by alonkeyval** [comment]
@Its-Aman-Yadav thanks, let me know if you need anything :)

**Comment by Its-Aman-Yadav** [comment]
@blumamir Thank you so much for assigning me this issue, I have started my work and @alonkeyval would let you know when I need any help :)
