### ISSUE TITLE
feat : Add CSS to the footer section (Home , blog, Pricing ) 

### ISSUE THREAD

**Issue by YashkShrivas4491** [keyval-dev/odigos#623]
**Is your feature request related to a problem? Please describe.**
 1. Add CSS to the footer section (Home , blog, Pricing )  while hovering the text it color gets sync with website background color
 2. Text is not visible clearly
  
  https://github.com/keyval-dev/odigos/assets/87111197/2ba1ed50-661f-4d6a-a106-d3145d4371e6

**Describe the solution you'd like**
  so, I would like to work on this section (To change the CSS of the footer text)

**Describe alternatives you've considered**

**Additional context**
 so could you  assign me this issue

**Comment by YashkShrivas4491** [comment]
@edeNFed I would like to work on this issue can you assign me

**Comment by JatinPhogat** [comment]
Hi @YashkShrivas4491 , I have done this type of work earlier in my own project. Please assign this issue to me so that i can start working on it.

**Comment by SudeeptaGiri** [comment]
Hello @YashkShrivas4491 I want to do this task, Please assign this Issue to me.

**Comment by YashkShrivas4491** [comment]
> @edeNFed I would like to work on this issue can you assign me



> Hello @YashkShrivas4491 @edeNFed I want to do this task, Please assign this Issue to me.

Dude, actually I m not the maintainer of this repo I'm also asking them to assign me

**Comment by YashkShrivas4491** [comment]
> Hi @YashkShrivas4491 , I have done this type of work earlier in my own project. Please assign this issue to me so that i can start working on it.

Dude, actually I m not the maintainer of this repo I'm also asking them to assign me

**Comment by nrhitik** [comment]
I would like to work on this issue. could you please assign me this issue.

**Comment by alonkeyval** [comment]
assigned to @YashkShrivas4491

**Comment by YashkShrivas4491** [comment]
> assigned to @YashkShrivas4491

Due to some health issue sorry for the delay I will try to do it asap
