### ISSUE TITLE
Want to add project setup guide in readme 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [keyval-dev/odigos#639]
pls assign me this issue

**Comment by blumamir** [comment]
Thanks @AnshuPathak-88825 .

**Comment by AnshuPathak-88825** [comment]
working on it

**Comment by chinmay7016** [comment]
pls assign me this issue

**Comment by chinmay7016** [comment]
> > pls assign me this issue
> 
> Thanks @chinmay7016 . It seems @AnshuPathak-88825 is already working on this.

Sorry sir for the disrespect but there is still no updates from sir Anshu Pathak side

**Comment by AnshuPathak-88825** [comment]
I'm little bit busy with my college report I'll complete it soon
