### ISSUE TITLE
some Golang and Java language services cannot be recognized

### ISSUE THREAD

**Issue by Shulong123** [keyval-dev/odigos#65]
**Describe the bug**
some Golang and Java language services cannot be recognized.
eg.
![image](https://user-images.githubusercontent.com/15952709/217139154-4acbded2-c275-48ee-ba58-6346160ade83.png)

**Expected behavior**
i expect that all Java , Golang and Python language service can be recognized.

**Desktop (please complete the following information):**
AWS EKS 1.21

**Additional context**
what can i do next?

**Comment by Shulong123** [comment]
i use odigos image : ghcr.io/keyval-dev/odigos/odiglet:v0.1.38.

**Comment by edeNFed** [comment]
Hi @Shulong123 
We improved Go and Java language detection in version v0.1.46.
Can you please try again with a more recent version?
