### ISSUE TITLE
Do not inject monitoring, system, logging and other related namespaces

### ISSUE THREAD

**Issue by jingslunt** [keyval-dev/odigos#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by eugercek** [comment]
I'm not sure I understood your problem correctly, but if you want to ignore some namespaces for odigos functionality. There's [`ignoredNamespaces`](https://github.com/keyval-dev/odigos-charts/blob/master/charts/odigos/values.yaml#L24-L29) field you can use this.

**Comment by aslafy-z** [comment]
I'd prefer to include to the namespaces I want to be injected instead of excluding some of them. Also, my list is dynamic, I'd like to specify a namespace selector (`matchLabels` or `matchExpressions`, I guess the best would be to allow both options) instead of a static list.

**Comment by edeNFed** [comment]
Writing a summary of all the comments just to make sure we are all on the same page:

We should probably support 4 ways to select the target applications:
1. **Opt out**: instrument everything besides well-known ignored namespaces (kube-system,etc)
2. **Opt out + additional ignored namespaces**: instrument everything besides the selected namespaces (as @eugercek said this is possible by using the `ignoredNamespaces` feature).
3. **Opt in (applications scope)**: select specific applications by name / labels / annotations
4. **Opt in (namespace scope)** - select specific namespaces by name / labels / annotations

Does that sound right to everyone? can you think of a use case that we don't cover using these 4 ways to select applications?
