### ISSUE TITLE
Print nice message when odigos install is called when odigos is already installed

### ISSUE THREAD

**Issue by blumamir** [keyval-dev/odigos#660]
Currently, when odigos is already installed, and one calls `odigos install`, the following output is ejected to console:
```
➜ odigos install
Installing Odigos version v0.1.75 in namespace odigos-system ...
Creating namespace odigos-system                  X
ERROR namespaces "odigos-system" already exists
```

I think it would be nicer to print some useful friendly message, like:
```
Odigos is already installed in namespace "odigos-system".
If you wish to re-install, run "odigos uninstall" first.
```

**Comment by blumamir** [comment]
@HeetVekariya Since you are already working on the `odigos uninstall` fix, would you be interested in fixing this one as well?

**Comment by blumamir** [comment]
To check if odigos is already installed, one can use [GetOdigosNamespace](https://github.com/keyval-dev/odigos/blob/609985701c758032f58a030b7ed35b765dfd61ce/cli/cmd/resources/namespace.go#L21) function to check if there is an existing `odigos` installation in the cluster.

**Comment by HeetVekariya** [comment]
- @blumamir Sorry for the silence, as i was in college.
- I see that you have assigned me two issue, thank you for that.

**Comment by HeetVekariya** [comment]
closed this as completed
