### ISSUE TITLE
Bug : Expected full stops at the end of each feature's description.

### ISSUE THREAD

**Issue by ayushrakesh** [keyval-dev/odigos#661]
**Describe the bug**
Absence of full stops at the end of each feature in Home page. I have attached the screenshot of it you can see below inside the screenshot section.
Link- [Link here of that home page.](https://odigos.io/) 

**Expected behavior**
As you can see in the screenshots , there should be full stop after each description of features in Home page.

**Screenshots**
![IMG_20231018_113307](https://github.com/keyval-dev/odigos/assets/115995339/1d648654-e62c-4ebe-be53-c38d0443c7b9)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser - Chrome
 - Version - v0.1.79

Please assign this issue to me.

**Comment by alonkeyval** [comment]
@ayushrakesh what do you mean by "full stops" at the end?

**Comment by ayushrakesh** [comment]
means there should be full stops in feature's description ,in main page (home).  I have provided screenshot.

**Comment by alonkeyval** [comment]
@ayushrakesh for example, instead of "Get started in minutes, without having to change a single line of code. Just select an observability backend and that`s it" -> "Get started in minutes, without having to change a single line of code. Just select an observability backend and that`s it**.**"?

**Comment by ayushrakesh** [comment]
> @ayushrakesh for example, instead of "Get started in minutes, without having to change a single line of code. Just select an observability backend and that's it" -> "Get started in minutes, without having to change a single line of code. Just select an observability backend and that's it **.** "?

Exactly what I meant and for all cards also..

**Comment by alonkeyval** [comment]
great, you can do it :) @ayushrakesh
