### ISSUE TITLE
Restructure Router Folder for Improved URL Structure

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#669]
**Issue Description:**

The current structure of our router folder could benefit from a more organized and understandable layout. We aim to reorganize it by creating a Next.js route group for the 'overview' section, which will contain the following routes:

- overview
- destinations
- sources

**Scope of Work:**

Create a new route group named 'overview' within the router folder.
Inside the 'overview' route group, add routes for 'overview,' 'destinations,' and 'sources.'
Ensure that the routes are configured correctly, matching their respective components or page files.
Update the navigation links and any references to these URLs to reflect the new structure.
Ensure that all existing functionality and data retrieval are maintained during this restructuring.
Test the updated structure to confirm that it works as intended.

**Skills Needed:**
- Proficiency in Next.js routing and folder structure.
- Knowledge of JavaScript and web development.
- Experience with route handling and navigation.

**Expected Outcome:**
The restructuring of the router folder will result in a more logical and organized URL structure, making it easier for developers and users to understand and navigate our project. This improved structure should contribute to a better overall user experience and maintain the integrity of our existing functionality.

**Note**: Adapt this issue to the specific needs and technologies used in your project. Be sure to provide more details and context in the actual issue description when creating it in your repository.

**Comment by Kritik-J** [comment]
@alonkeyval I would like to work on it, Please assign this to me

**Comment by alonkeyval** [comment]
@Kritik-J Good luck!
