### ISSUE TITLE
Add Hover Animation to Navigation Menu Titles

### ISSUE THREAD

**Issue by Abhishek19-dev** [keyval-dev/odigos#675]
**Is your feature request related to a problem? Please describe.**
I've noticed that the navigation menu titles in the odigos project lack interactive feedback when users hover over them. This can lead to a less engaging user experience and make it harder for users to understand which menu item they are interacting with.

**Describe the solution you'd like**
I would like to add a hover animation to the navigation menu titles (e.g., 'Home,' 'Blog,' 'Pricing,' 'Documentation') in the Odigos project. When users hover over these menu titles, they should change in appearance (eg color) to provide visual feedback and enhance the user experience.

**Additional context**
I will add same color  as join waitlist button hover .

**Comment by alonkeyval** [comment]
@Abhishek19-dev Thanks, we have an open issue regarding this.
