### ISSUE TITLE
Lacks Email Validation + Button inconsistency

### ISSUE THREAD

**Issue by myselfprincee** [keyval-dev/odigos#677]
**Describe the bug**
Issues in https://odigos.io/waitlist

There is no Email Validation, I am submit Blank to the url. + Loading animation is also not visible during the button click.

See the Video 👇
https://github.com/keyval-dev/odigos/assets/114233864/0a11c715-1f2e-40de-8621-f226e6febd93

**To Reproduce**
https://odigos.io/waitlist 
<img width="398" alt="image" src="https://github.com/keyval-dev/odigos/assets/114233864/9f9ea75a-e9b0-417d-8bb4-c8ff47e2acd5">
Enter a Space in Work Email and Click Join the Waitlist

**Expected behavior**
Work Email should include appropriate validation for Emails and the loading state should be visible after Clicking the Button.

**Desktop (please complete the following information):**
 - OS: Winodows 11
 - Browser Google Chrome

**Additional context**
Please Assign this issue to me I would love to work on this @edeNFed

**Comment by alonkeyval** [comment]
The issue has already been resolved, @myselfprincee. Thank you for bringing it to our attention.

**Comment by myselfprincee** [comment]
> The issue has already been resolved, @myselfprincee. Thank you for bringing it to our attention.

You're Welcome
