### ISSUE TITLE
Join Waitlist opens a New Tab everytime

### ISSUE THREAD

**Issue by myselfprincee** [keyval-dev/odigos#678]
**Describe the bug**
After clicking the join waitlist button, the Website is getting opened everytime in a new tab.

https://github.com/keyval-dev/odigos/assets/114233864/359f6202-4e8b-4b12-a151-9b83bdfd6452

**To Reproduce**
go to https://odigos.io/waitlist
Then Click on Join Waitlist of Navbar

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Google Chrome
 - Version 118.0.5993.89 (Official Build) (64-bit)

**Additional context**
Please assign me the issue I would love to fix it @edeNFed

**Comment by Ritish134** [comment]
Please assign me the issue I would love to fix it @edeNFed

**Comment by myselfprincee** [comment]
Bro I saw the Issue and Told @edeNFed to Assign it to me. If I will be unable to do it then you should Ask Why You're not giving a chance to your Junior 🥲

**Comment by myselfprincee** [comment]
> Please assign me the issue I would love to fix it @edeNFed 

See at the end of the issue

**Comment by alonkeyval** [comment]
thanks @myselfprincee, this is the expected behavior
