### ISSUE TITLE
Opensearch Destination

### ISSUE THREAD

**Issue by ThisIsQasim** [keyval-dev/odigos#69]
**Is your feature request related to a problem? Please describe.**
We have an ELK-like stack (FLOOD stack?) with OpenSearch for monitoring and observability. This project would be a game changer if OpenSearch was supported as a destination.

**Describe the solution you'd like**
OpenSearch as log/metric/trace destination for odigos

**Comment by edeNFed** [comment]
Hi @ThisIsQasim we just released version v0.1.4 with support for Elasticsearch.
AFAIK OpenSearch and Elasticsearch use the same wire format so it should work for OpenSearch as well.
Please give it a try and let me know if there are any problems.

**Comment by ThisIsQasim** [comment]
Impeccable timing 😀. I will try and report back if I find any compatibility issues.
