### ISSUE TITLE
NO image of user or avatar

### ISSUE THREAD

**Issue by lokendarjangid** [keyval-dev/odigos#693]
**Describe the bug**
It doesn't show the image of user or avatar.

**Expected behavior**

There is no image or avatar for user on the left side of username and it is empty.

**Screenshots**
![Screenshot from 2023-10-23 18-39-29](https://github.com/keyval-dev/odigos/assets/57801045/67f17fd1-b4a4-4270-96a4-d9eca638b228)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser : Brave
 - Version : 1.59.120

**Comment by alonkeyval** [comment]
@lokendarjangid  we do not collect any user information, and therefore, this feature is not supported.
