### ISSUE TITLE
service name is odiglet for go instrumented code

### ISSUE THREAD

**Issue by mittalsuraj18** [keyval-dev/odigos#694]
**Describe the bug**
All the go code traces come under the service odiglet. 

**To Reproduce**
1. Install via steps followed on docs.
2. Auto instrument any go code apart from odiglet.

**Expected behavior**
the traces should be collected under the relevant service name instead of the service name odiglet.

Version: v0.1.82

Reverting to v.0.1.79 fixes the issue.

**Comment by edeNFed** [comment]
@RonFed Please take a look. Maybe this is related to your Go auto instrumentation change?
