### ISSUE TITLE
Not able to add a source - odigos-data-collection pod is failing - CrashLoopBackOff

### ISSUE THREAD

**Issue by QAInsights** [keyval-dev/odigos#702]
**Describe the bug**
While trying to add a source from my local k8s cluster, Odigos data collection pod is not starting eventually going into `CrashLoopBackOff`.

**To Reproduce**
1. Deploy a k8s cluster
2. Install Odigos
3. Launch Odigos UI to add a source

**Expected behavior**
Source should successfully gets added.

**Screenshots**
![image](https://github.com/keyval-dev/odigos/assets/2826376/42ff880e-315d-454f-9ed9-f92dd5b0fcc3)

**Desktop (please complete the following information):**
 - MacOS

**Smartphone (please complete the following information):**
```
Odigos Cli Version: version.Info{Version:'v0.1.83', GitCommit:'3d0074f', BuildDate:'2023-10-24T11:20:12Z'}
Odigos Version (in cluster): version.Info{Version:'v0.1.83'}

kubectl version                                                                                                                                           1git:(main) ✗ ?
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.2
```
**Additional context**

**Comment by QAInsights** [comment]
Any updates please?

**Comment by rauno56** [comment]
@QAInsights, could you please try the latest version?
