### ISSUE TITLE
Add VictoriaMetrics destination 

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#72]
As VictoriaMetrics gains popularity, we would like to add it as a new destination in Odigos.

**Comment by eugercek** [comment]
May I pick this up. I've been curious about VictoriaMetrics since I saw its benchmarks 😄

**Comment by edeNFed** [comment]
Sure sounds great. Let me know if you need help 🙂

**Comment by josephlim75** [comment]
@eugercek is there any progress for this feature sending to Victoriametrics destination ?
