### ISSUE TITLE
UI thinks it has added services, but it has failed to do so

### ISSUE THREAD

**Issue by adamf-db** [keyval-dev/odigos#722]
**Describe the bug**
Odigos fails to add some services, despite the UI thinking it has added those services.

**To Reproduce**
1. Setup a kind cluster
2. Install an application - in my case - https://docs.pingcap.com/tidb-in-kubernetes/dev/get-started
3. Install odigos & the UI
4. In the UI, add jaeger as the destination
5. In the UI, add source -> switch to `tidb-cluster` namespace, add all services
6. Generate some activity in the application (in this case, I loaded a GB of data into a table & queried that table)
7. Notice that not all sources show up in the UI (don't forget to switch to the `tidb-cluster` namespace). Missing is `basic-tikv` especially.
8. Notice in the jaeger UI that traces aren't being sent from `basic-tidb` to jaeger, but `basic-pd` and the monitoring services do send traces

**Expected behavior**
All services are added and represented in the UI, and all services show traces.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X 13.6
 - Browser latest chrome

`kubectl logs` on the various odigos services don't show any errors.

**Comment by adamf-db** [comment]
odigos versioin 0.18.5

**Comment by blumamir** [comment]
Sorry for the late response.

We fixed a bunch of bugs related to this in the UI lately. if the issue is still relevant, please feel free to re-open or create a new one 🙏
