### ISSUE TITLE
cli: add --yes flag to uninstall command

### ISSUE THREAD

**Issue by blumamir** [keyval-dev/odigos#728]
Currently, the `uninstall` cli command prompt the user for confirmation:
```sh
odigos uninstall
About to uninstall Odigos from namespace odigos-system
Are you sure? [Y/n]: 
```

It could be nice if this command had a flag `--yes`/`-y` cli flag, that the user can set to disable the confirmation and apply the uninstall without asking the user for anything.
The change needs to be applied both [in code](https://github.com/keyval-dev/odigos/blob/main/cli/cmd/uninstall.go) and in the docs [here](https://github.com/keyval-dev/odigos/blob/main/docs/cli/odigos_uninstall.mdx)

**Comment by HeetVekariya** [comment]
I would like to work on this issue
