### ISSUE TITLE
Validate destinations URLs in frontend before saving

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#73]
Currently, the only validation the frontend performs is that the destination URL is a valid URL.
We can help users avoid typing the wrong URLs by performing more validations in the frontend before persisting the destination.
Examples of possible additional validations:

- **Elasticsearch**: URL should contain port `9200`
- **Generic OTLP**: URL should contain port `4317`
- **Datadog**: URL should be a [valid site](https://docs.datadoghq.com/getting_started/site/)
- and many more, we can probably think of a better validation for every destination. 

The first step in implementing this issue may be just validating a single destination in addition to thinking about a good design for validations in frontend.

**Comment by D-Lite** [comment]
Hi @edeNFed , is this issue still open? I will like to pick it up and resolve it. I am more interested about FE related issues on Open Source projects!

**Comment by D-Lite** [comment]
https://user-images.githubusercontent.com/44473671/231995937-88fa9c6d-13ff-435e-a5e0-71c186943adc.mp4


I was able to come up with an FE validation for the Elasticsearch and Generic OTLF urls.
Implementation was based on testing the URLs on the frontend against a **regex pattern**

**Comment by D-Lite** [comment]
This issue should be closed @edeNFed
