### ISSUE TITLE
Change Side Menu Behavior to Open on Click Instead of on Hover

### ISSUE THREAD

**Issue by alonkeyval** [keyval-dev/odigos#748]
Currently, our side menu opens on hover, which may not be the most user-friendly behavior for all users. To enhance the user experience and provide a more accessible and predictable interaction, we should change the side menu behavior to open when clicked.

**Expected Behavior:**
The side menu should open/close when the user clicks on it.

**Comment by HeetVekariya** [comment]
I would like to work on this issue, but I may start working on after 9/11 as my exams are going on.
If you find it correct please assign it to me.

**Comment by HeetVekariya** [comment]
@alonkeyval can assign me the issue as now I can work on it.

**Comment by alonkeyval** [comment]
@HeetVekariya  any update?
