### ISSUE TITLE
demo pod cannot be scheduled

### ISSUE THREAD

**Issue by liulwx** [keyval-dev/odigos#754]
the micro serivce demo pods can run at first, however, when I choose them and config tracing in odigos ui. it seems that a deployment is chagned ,the requirement need instrumentation.odigos.io/*
adservice-6f6ff95578-z9l2b               0/1     Pending   0          27m
adservice-86d6b9c645-gqhph               1/1     Running   0          34m

and because of this, the pod cannot be scheduled.

**Comment by liulwx** [comment]
Any body can help me?

**Comment by edeNFed** [comment]
Hi @liulwx we changed the demo applications we are using for the getting started guide.
You are welcome to check the new guide with improved and more stable demo applications.
