### ISSUE TITLE
Helm chart installation OR plain YAML manifests alternative to the non-infra-as-code CLI's

### ISSUE THREAD

**Issue by caiobegotti** [keyval-dev/odigos#794]
**Is your feature request related to a problem? Please describe.**
The only mention of a non-CLI installation of Odigos seems to be in https://github.com/keyval-dev/odigos/commit/02639256a750cfa8e0e7555954af046fc8140c23#diff-a05eabe73b3aa6a33cb03155d0630e9cb7b683301204bec9cd6a7d92d52e700d

I wonder if it's by design given it mentions a transiton away from Helm charts?

**Describe the solution you'd like**
Having something critical to the clusters like Odigo with a infra-as-code installation would not just be ideal but actually a base requirement in major setups. I'm afraid Odigos would be hard to set up in environments that expect either YAML manifests to be reviewed in advance or at least Helm charts to be available.

Would it be possible not to tie the setup to the CLI as much as today?

**Describe alternatives you've considered**
E.g. Cilium's Hubble (eBPF) and its UI used a CLI for installation in the past too and today it supports both solutions to make it easier for people to use it.

**Additional context**
From a security perspective giving admin access to someone to set up something like Odigos using only a CLI we can't review easily in CI/CD is hard to adopt.

`I'd be happy to help with this effort but it's not even clear to me what would be the main basic manifests needed to make a chart with them`

**Comment by caiobegotti** [comment]
Is https://github.com/keyval-dev/odigos-charts abandoned or set to be?

**Comment by thomaspetit** [comment]
Glad to contribute on this one too.. I currently already extended it locally in my helm chart (with the top one as a subchart).

The cool thing is, the logic for handling this seems to already be present:
* Detect existing Configmap: https://github.com/keyval-dev/odigos/blob/17c26cc090c304d672642acb0f46ee26eee51e5d/autoscaler/controllers/gateway/configmap.go#L73
* Patch existing Configmap: https://github.com/keyval-dev/odigos/blob/17c26cc090c304d672642acb0f46ee26eee51e5d/autoscaler/controllers/gateway/configmap.go#L81

**Comment by edeNFed** [comment]
Hi @caiobegotti @thomaspetit we will be happy to get contributions for this.
The current helm chat is not updated since we moved to CLI installation, but syncing it with the latest CLI should be easy.

All the different YAMLs can be converted from the go structs: https://github.com/keyval-dev/odigos/blob/main/cli/cmd/resources/instrumentor.go#L40-L62

**Comment by esara** [comment]
see https://github.com/keyval-dev/odigos-charts/pull/19 :-)

**Comment by blumamir** [comment]
Thanks to https://github.com/esara for updating the helm charts.

You are welcome to try https://github.com/keyval-dev/odigos-charts and notify us on any issues.

**Comment by blumamir** [comment]
If you have any more request or issues regarding the helm charts, feel free to open issue and PRs in the helm chart repo 🙏
