### ISSUE TITLE
No up-to-date image available for odigos UI on dockerhub

### ISSUE THREAD

**Issue by thomaspetit** [keyval-dev/odigos#798]
**Is your feature request related to a problem? Please describe.**

There are docker images available for odigos on dockerhub:
https://hub.docker.com/r/keyval/odigos-ui/tags

Following images have all been updated to v1.0.2:
keyval/odiglet-base
keyval/odigos-cli
keyval/odigos-odiglet
keyval/odigos-instrumentor
keyval/odigos-scheduler
keyval/odigos-autoscaler

While `odigos-ui` has not been released yet.

**Describe the solution you'd like**
Push a v1.0.2 image of `odigos-ui`under the keyval account on dockerhub

**Comment by thomaspetit** [comment]
@edeNFed it seems I'm having difficulty to even build the latest frontend, am I missing something?

**Comment by thomaspetit** [comment]
I had some opportunity to work on it too past days (during spare time on conference). It seems to me that this dockerfile that we provisioned in the `frontend` folder was completely incorrect. So far I've refactored already 50% to make it work and run the code. Locally I can get it to work (without containers) but I came to pretty much the same conclusion.

It's really weird.. Feels like things were rushed and not checked in? :)

**Comment by edeNFed** [comment]
Hi @thomaspetit can you please let me know what is the problem with the current `Dockerfile`?
I can build it successfully by executing:
```shell
docker build -t dev/frontend:dev . -f frontend/Dockerfile
```
from the root directory of the Odigos repository. Also seems like GitHub action is also [working](https://github.com/keyval-dev/odigos/actions/runs/7158480271/job/19490611027)

**Comment by thomaspetit** [comment]
@edeNFed I've wiped my podman vm (deleting all my images) and wiped the git repo I cloned locally and confirm it now builds. Among many issues, this was one of them:
```
TS2786: 'ThemeProvider' cannot be used as a JSX component.
Its instance type 'Component<ThemeProviderProps<any, any>, any, any>' is not a valid JSX element.
The types returned by 'render()' are incompatible between these types.
```
