### ISSUE TITLE
Deployment and StatefulSet with same name may overwrite each other

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#8]
Use generated name for `InstrumentedApplication` instead of fixed name

**Comment by brunocascio** [comment]
what about using the `namespace` as part of the name?

**Comment by eugercek** [comment]
If @brunocascio is not working on this issue, may I pick this up?

**Comment by brunocascio** [comment]
> If @brunocascio is not working on this issue, may I pick this up?

Go ahead 👍

**Comment by eugercek** [comment]
I couldn't start in this weekend, I'll start in this monday. This is my current roadmap:

1. Provide reproduce steps, I'll give simple bash script with imperative kubectl commands to reproduce
2. Read previous PRs related to this issue
3. Find "generated name" examples, I'm not sure how that name is supposed to be
4. Implement code, if It's possible add unit tests previously

**Comment by edeNFed** [comment]
Sounds great @eugercek Let me know if I can help

**Comment by eugercek** [comment]
I managed to reproduce:

```bash
k create deploy foo --image stefanprodan/podinfo
cat <<EOF > sts.yaml
apiVersion: v1
kind: Service
metadata:
  name: foo
  labels:
    app: foo
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: foo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foo
spec:
  serviceName: "foo"
  replicas: 2
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: nginx
        image: stefanprodan/podinfo
        ports:
        - containerPort: 80
          name: web
k apply -f sts.yaml
```

With above those two name collides, and only first one is shown in `k get instrumentedapplications` in logs of `odigos-instrumentor` there's following error, removed the stack trace (This is the longest stack trace I've ever seen in Go, k8s is beast 😃 )
```
1.67452148985932e+09    INFO    controller.statefulset  not enough ready replicas, waiting for pods to be ready {"reconciler group": "apps", "reconciler kind": "StatefulSet", "name": "foo", "namespace": "default"}
1.6745214899019861e+09  INFO    controller.statefulset  not enough ready replicas, waiting for pods to be ready {"reconciler group": "apps", "reconciler kind": "StatefulSet", "name": "foo", "namespace": "default"}
1.67452149323941e+09    ERROR   controller.statefulset  error creating InstrumentedApp object   {"reconciler group": "apps", "reconciler kind": "StatefulSet", "name": "foo", "namespace": "default", "error": "instrumentedapplications.odigos.io \"foo\" already exists"}
```
---

I have two questions @edeNFed 
1. I couldn't find similar PRs, could you point me to some lines in codebase, to fasten me (only file:sloc no explanation) 🙇🏻 
2. What should be the generated name, ,maybe we can `ObjectType-Name` like `Deployment-foo` or `dep-foo`. I'm not aware of best practices in crd naming. But I've read some objects can not have `/` in their names maybe we should avoid that.

**Comment by edeNFed** [comment]
Sure:
1. I think the following file is a good place to start:
https://github.com/keyval-dev/odigos/blob/main/instrumentor/controllers/common.go#L40-L65
2. `ObjectType-Name` is good.
After you change this maybe its worth also making a change in the UI to not show `ObjectType-Name` as the application name but only `Name` (there is already a field shown in the UI that indicates the ObjectType). You may also want to check out these files:
https://github.com/keyval-dev/odigos/blob/main/ui/pages/api/apps.ts#L41-L48
https://github.com/keyval-dev/odigos/blob/main/ui/pages/api/source/%5Bnamespace%5D/%5Bname%5D.ts#L4
