### ISSUE TITLE
website: Jaeger logos with transparent eyes are scary on the dark background

### ISSUE THREAD

**Issue by ccmtaylor** [keyval-dev/odigos#822]
**Describe the bug**
The Jaeger logos on https://odigos.io have transparent eyes instead of white. Combined with the dark site background, it produces a pretty unsettling effect:

![image](https://github.com/keyval-dev/odigos/assets/425325/26abd5e3-94ab-4e78-bc09-cebc71180334)

**To Reproduce**
1. Go to https://odigos.io/
2. Scroll down to the section titled "Seamless Integration with any APM"
3. Become a monster while the abyss gazes back into you

**Expected behavior**
A  ̴c̸l̸e̶a̵r̶ ̵an̸̡̆d conci̴̬̍s̶̱̀e description of what̶̢͝ you expected to happen.

**Screenshots**
![image](https://github.com/keyval-dev/odigos/assets/425325/26abd5e3-94ab-4e78-bc09-cebc71180334)

**Comment by RonFed** [comment]
In the updated website it looks right
