### ISSUE TITLE
Add quickwit in available observability backends

### ISSUE THREAD

**Issue by fmassot** [keyval-dev/odigos#865]
Hi there, [quickwit](https://github.com/quickwit-oss/quickwit) team here. We are a storage backend for logs and traces and we think that Odigos and Quickwit is a very good match, I think it's worth adding a Quickwit observability backend.

**Is your feature request related to a problem? Please describe.**
Support for sending logs and traces to Quickwit

**Describe the solution you'd like**
Quickwit supports the OTLP gRPC API for logs and traces and, soon, the HTTP API.

**Describe alternatives you've considered**
Using the the generic OpenTelemetry backend.

If you support it, we can give it a try and open a PR. What do you think?

**Comment by idrissneumann** [comment]
Hi.

I started a PR here: #907 it's still WIP but I'd like to know if there's a way to make a quick test injecting events with a docker compose or something like that somewhere @edeNFed (without having to build and deliver images to a registry to deploy it in a kind or k3d cluster). Thanks in advance :)

No problem if it's not the case.

Thanks

**Comment by edeNFed** [comment]
Hi @idrissneumann 
I think the easiest way to test Odigos locally would be using `kind`.
You do not need to upload the images to any registery just run from the repository root directory:
`TAG=<current odigos version> make build-images load-to-kind`

This command will build all the Odigos images with your changes and will load them to kind, so when you run `odigos install` all the images are already loaded and Odigos will start with your code changes.
Hope that helps, please let me know if you are having any issues

**Comment by idrissneumann** [comment]
Hello.

I think we can close this issue. The #907 has been merged and it's working in the last release v1.0.49 :)

A quick demo with OTEL logs here:

https://github.com/keyval-dev/odigos/assets/12884347/c4c265ce-1664-48a4-9921-0b19e89e0547

You can reproduce the test with the following repo: https://github.com/quickwit-oss/odigos-test

**Comment by blumamir** [comment]
Amazing! Thank you so much for contributing and recording the demo 🙏
