### ISSUE TITLE
export the logs to OSS Loki is not working after v1.0.12 

### ISSUE THREAD

**Issue by edwardwu** [keyval-dev/odigos#878]
**Describe the bug**
when shipping the logs to loki, the error occurred after upgrade to v1.0.15 and it was working fine on v1.0.11 

Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'exporters': error reading configuration for "loki/loki": 1 error(s) decoding:
* '' has invalid keys: labels
2024/01/07 18:39:05 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'exporters': error reading configuration for "loki/loki": 1 error(s) decoding:
* '' has invalid keys: labels

**To Reproduce**
1. odigos upgrade (from v1.0.11 -> v1.0.15)
2. update the Loki Destination 
3. check the pod status
odigos-gateway-6944f58fd-92s24        0/1     CrashLoopBackOff   5 (47s ago)   3m43s
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'exporters': error reading configuration for "loki/loki": 1 error(s) decoding:
* '' has invalid keys: labels

**Expected behavior**
An odigos-gateway pod is Running

**Comment by edwardwu** [comment]
some findings
from         containerImage       = "keyval/otel-collector-contrib:v0.4"
to         containerImage       = "keyval/otel-collector-contrib:v0.6"
and
use collector/odigosotelcol/go.mod:37:	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/lokiexporter v0.91.0

**Comment by edeNFed** [comment]
@edwardwu this is resolved in the latest Odigos release. Please let me know if you have any more issues.
