### ISSUE TITLE
Add `--short` flag to odigos version command

### ISSUE THREAD

**Issue by edeNFed** [keyval-dev/odigos#902]
Currently running `odigos version` will print the full version of the CLI and the version installed on the current cluster.
I propose adding a new flag which can be used like: `odigos version --short`, this flag will return only the current version of the CLI without any additional data.
for example
```bash
> odigos install --short
v1.0.21
```

By implementing this feature we will be able to automatically get the current version in the `Makefile` without having to specify `TAG` env var.

**Comment by WallysFerreira** [comment]
I'd like to work on this

**Comment by blumamir** [comment]
> I'd like to work on this

Thanks @WallysFerreira , please reach out if you need any help with this

**Comment by WallysFerreira** [comment]
I think I'm almost set to go, but there's an error on installation that does not let me test the flag.

![Screenshot of error on console](https://github.com/keyval-dev/odigos/assets/105322824/da595877-6791-4442-b0ab-8e7d055f63b8)

**Comment by blumamir** [comment]
When you execute `go run . install` from the code, you need to specify the version you are installing like this:
`go run . install --version v1.0.27`.

For official releases, the version is embedded in the CI, but for development you need to set it directly

**Comment by blumamir** [comment]
added in #939
