### ISSUE TITLE
Docs do not include configuring AWS S3 backend

### ISSUE THREAD

**Issue by razvi-razorpay** [keyval-dev/odigos#903]
**Describe the bug**
In the [docs](https://docs.odigos.io/overview) Observability Backends section, there is no section for configuring and using AWS S3 while it is supported.
**To Reproduce**
1. Go to https://docs.odigos.io/
2. Scroll down to Observability Backends section
4. See that AWS S3 is not listed there

**Expected behavior**
The documentation should give clear steps to integrate AWS S3 as backend

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by blumamir** [comment]
Hi @razvi-razorpay ,

Thanks for letting us know it is missing. We will add the relevant part to the docs soon, in the meantime, please find instructions on using the s3 destination in [this blog post](https://odigos.io/blog/sending-otel-to-s3). Please let us know if there is anything else missing in the docs or any other suggestions for improvements 🙏

**Comment by blumamir** [comment]
@razvi-razorpay I opened a PR that enhances this exporter + introduces docs on how to use it in the documentation website. Feel free to drop any comments or suggestions for improvement in the PR.

Thanks for bringing it up and letting us know the docs are missing
