### ISSUE TITLE
Remove Hardcoded Elasticsearch Port

### ISSUE THREAD

**Issue by clavinjune** [keyval-dev/odigos#940]
**Is your feature request related to a problem? Please describe.**
The problem is, my elasticsearch is not running on port 9200, I want to have flexibility on the port configuration
https://github.com/keyval-dev/odigos/blob/206ef74eccff945a582571186365d2410d76347d/autoscaler/controllers/gateway/config/elasticsearch.go#L39
https://github.com/keyval-dev/odigos/blob/206ef74eccff945a582571186365d2410d76347d/autoscaler/controllers/gateway/config/elasticsearch.go#L59

**Describe the solution you'd like**
We can remove the hardcoded port, and also make sure that user put a valid URL by validating it using `url.Parse`

**Describe alternatives you've considered**
-

**Additional context**
I can work on this issue

**Comment by edeNFed** [comment]
Thanks for opening the issue @clavinjune we will be happy to accept a PR that fixes this. Let me know if I can help

**Comment by clavinjune** [comment]
could you please assign this issue to me @edeNFed? thank you

**Comment by clavinjune** [comment]
hi @blumamir / @edeNFed any plan to deploy this in the near future?
