### ISSUE TITLE
Sort backends list in alphabetic order in docs

### ISSUE THREAD

**Issue by blumamir** [keyval-dev/odigos#943]
The list of Observability Backends in the odigos docs is currently not in alphabetic order. I suggest sorting it so it is easier to find the relevant backend in the list.

The fix needs to be made in 2 places:
[mint.json](https://github.com/keyval-dev/odigos/blob/fa9ad93f28c8e0d5f87c77dab6d915be6c0f3081/docs/mint.json#L65)
[next-steps.mdx](https://github.com/keyval-dev/odigos/blob/fa9ad93f28c8e0d5f87c77dab6d915be6c0f3081/docs/next-steps.mdx#L20)

**Comment by ankur0904** [comment]
@blumamir Can I work on this issue?

**Comment by blumamir** [comment]
> @blumamir Can I work on this issue?

Thank you

**Comment by ankur0904** [comment]
I submitted the PR.
